services:
  titiler-pgstac:
    image: ianhorn/stac-fastapi-pgstac-lambda-layer
    container_name: sfap-layer
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash", "create-lambda-layer.sh"]